name: Test and build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY_SECRET }}
    - name: Run
      run: cargo test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY_SECRET }}

    - name: Build binary
      run: docker run --rm -u root -v ${HOME}/.ssh:/root/.ssh -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -v `pwd`:/home/rust/src ekidd/rust-musl-builder cargo build --release

    - name: save artifacts -- proxy-server
      uses: actions/upload-artifact@v2
      with:
        name: proxy-server
        path: ./target/x86_64-unknown-linux-musl/release/proxy-server

    - name: save artifacts -- proxy-client
      uses: actions/upload-artifact@v2
      with:
        name: proxy-client
        path: ./target/x86_64-unknown-linux-musl/release/proxy-client